/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        inst: {
          canvas: 'var(--color-canvas)',
          surface: 'var(--color-surface)',
          subtle: 'var(--color-subtle)',
          inset: 'var(--color-inset)',
          primary: 'var(--color-primary)',
          secondary: 'var(--color-secondary)',
          muted: 'var(--color-muted)',
          border: 'var(--color-border)',
          'border-strong': 'var(--color-border-strong)',
          warning: 'var(--color-warning)',
          danger: 'var(--color-danger)',
          info: 'var(--color-info)',
        },
        fuelguard: {
          green: 'var(--fuelguard-green)',
          'green-hover': 'var(--fuelguard-green-hover)',
          'green-light': 'var(--fuelguard-green-light)',
          'green-border': 'var(--fuelguard-green-border)',
        },
        permity: {
          lime: '#d4f63d',
          'lime-hover': '#c5ea2d',
          'lime-light': '#f4fcd4',
          dark: '#111827',
          'dark-hover': '#1f2937',
          'dark-card': '#0f172a',
          canvas: '#f4f5f7',
          surface: '#ffffff',
          subtle: '#f8f9fa',
          border: '#e2e8f0',
        },
      },
      fontFamily: {
        display: ['var(--font-display)', 'system-ui', 'sans-serif'],
        ui: ['var(--font-ui)', 'system-ui', 'sans-serif'],
        mono: ['var(--font-mono)', 'ui-monospace', 'monospace'],
      },
      borderRadius: {
        xs: '2px',
        sm: '4px',
        md: '6px',
        lg: '8px',
        xl: '12px',
        '2xl': '16px',
        '3xl': '24px',
        '4xl': '32px',
        full: '9999px',
      },
      boxShadow: {
        hairline: '0 0 0 1px var(--color-border)',
        raised: '0 1px 3px rgba(0, 0, 0, 0.08), 0 0 0 1px var(--color-border)',
        overlay: '0 8px 24px rgba(0, 0, 0, 0.25), 0 0 0 1px var(--color-border-strong)',
        permity: '0 2px 12px rgba(0, 0, 0, 0.04)',
        'permity-lg': '0 8px 30px rgba(0, 0, 0, 0.08)',
        'permity-card': '0 1px 3px rgba(0, 0, 0, 0.05), 0 10px 24px -5px rgba(0, 0, 0, 0.04)',
      },
    },
  },
  plugins: [],
}
