/**
 * FuelGuard Virtual Test Bench — Cenários Pré-configurados Oficiais (Seção 11 do Briefing)
 */

import { SimulationScenario } from './scenario-types';

export const BUILT_IN_SCENARIOS: SimulationScenario[] = [
  {
    id: 'nominal',
    name: 'Cenário A: Operação Nominal Estável',
    badge: 'Padrão',
    description: 'Nível intermediário estável, sem agitação, sensor alinhado, tag NFC autorizada cadastrada e conexão online.',
    initialWaterHeightCm: 57.7,
    temperatureC: 24.8,
    noiseStdDevCm: 0.2,
    initialLidClosed: true,
    initialNfcUid: '04:3A:7F:2C:5D',
    initialSloshAmplitudeCm: 0.0,
    transportOnline: true,
    stepDescription: [
      'Nível em 57.7% estável',
      'Tampa fechada',
      'Operador autorizado identificado',
      'Sem perda de pacotes',
    ],
  },
  {
    id: 'slosh',
    name: 'Cenário B: Abastecimento Rápido & Slosh',
    badge: 'Dinâmico',
    description: 'Entrada abrupta de água gerando oscilações harmônicas de superfície, testando a resposta do filtro mediano.',
    initialWaterHeightCm: 65.0,
    temperatureC: 24.8,
    noiseStdDevCm: 1.8,
    initialLidClosed: true,
    initialNfcUid: '04:3A:7F:2C:5D',
    initialSloshAmplitudeCm: 6.0,
    transportOnline: true,
    stepDescription: [
      'Degrau no nível de água para 65 cm',
      'Ondulação superficial de 2.5 Hz com decaimento exponencial',
      'Filtro mediano suavizando oscilações transitórias',
    ],
  },
  {
    id: 'blind_zone',
    name: 'Cenário C: Obstrução & Zona Cega (< 20 cm)',
    badge: 'Falha Acústica',
    description: 'Nível da água se aproxima a menos de 20 cm do sensor, gerando eco na zona de anelamento piezoelétrico.',
    initialWaterHeightCm: 85.0, // Href=100cm -> d=15cm (< 20cm)
    temperatureC: 25.0,
    noiseStdDevCm: 4.5,
    initialLidClosed: true,
    initialSloshAmplitudeCm: 0.0,
    transportOnline: true,
    stepDescription: [
      'Coluna d\'água atinge 85 cm (distância = 15 cm)',
      'Violação da cota mínima de 20 cm do transdutor JSN-SR04T',
      'Transição do ESP32 para estado ALERT_SENSOR',
      'Flag de eco inválido emitida na telemetria',
    ],
  },
  {
    id: 'unauthorized_nfc',
    name: 'Cenário D: Tag NFC Não Autorizada',
    badge: 'Segurança Didática',
    description: 'Apresentação de cartão com UID desconhecido (04:9B:11:3E:8A). Emissão de evento nfc.denied sem abrir sessão.',
    initialWaterHeightCm: 57.7,
    temperatureC: 24.8,
    noiseStdDevCm: 0.2,
    initialLidClosed: true,
    initialNfcUid: '04:9B:11:3E:8A',
    initialSloshAmplitudeCm: 0.0,
    transportOnline: true,
    stepDescription: [
      'Leitura de UID desconhecido pela leitora PN532',
      'Emissão de evento canônico nfc.denied',
      'Nenhuma sessão de abastecimento iniciada',
    ],
  },
  {
    id: 'lid_chatter',
    name: 'Cenário E: Abertura da Tampa com Rebote',
    badge: 'Debounce 50ms',
    description: 'Abertura do reed switch gerando rajada mecânica de 10 pulsos em 15 ms, testando a estabilização do debounce de 50 ms.',
    initialWaterHeightCm: 57.7,
    temperatureC: 24.8,
    noiseStdDevCm: 0.2,
    initialLidClosed: false,
    initialSloshAmplitudeCm: 0.0,
    transportOnline: true,
    stepDescription: [
      'Abertura física da tampa',
      'Rajada de 10 a 12 micro repiques mecânicos',
      'Filtro de debounce do ESP32 aguarda 50 ms antes de disparar o alerta',
      'Transição para ALERT_TAMPER',
    ],
  },
  {
    id: 'offline_queue',
    name: 'Cenário F: Queda de Rede & Fila Offline',
    badge: 'Resiliência IoT',
    description: 'Desconexão do transporte virtual durante abastecimento, acumulando eventos na fila com replay ordenado.',
    initialWaterHeightCm: 50.0,
    temperatureC: 24.8,
    noiseStdDevCm: 0.5,
    initialLidClosed: true,
    initialNfcUid: '04:3A:7F:2C:5D',
    initialSloshAmplitudeCm: 0.0,
    transportOnline: false,
    stepDescription: [
      'Corte da conexão virtual de rede',
      'Armazenamento local ordenado de eventos no buffer offline',
      'Manutenção estrita dos timestamps sim_time_ms e números de sequência',
      'Replay cronológico quando a rede é restabelecida',
    ],
  },
];
