/** Catálogo CAD da configuração real da bancada FuelGuard. */

export type CadModelValidation = 'exact_verified' | 'documented_reference' | 'vendor_lot_specific' | 'site_specific' | 'didactic_approximate' | 'passive_parametric';
export type CadConfidenceLevel = 'A' | 'B' | 'C' | 'D';

export interface ComponentPinDefinition {
  id: string; pinNumber: number; label: string;
  signalType: 'power' | 'ground' | 'digital_in' | 'digital_out' | 'passive' | 'spi_clock' | 'spi_data';
  nominalVoltageV: number; description: string; relativeX: number; relativeY: number;
}

export interface CadComponentMetadata {
  id: string; designatorPrefix: string; name: string; manufacturer: string; partNumber: string; revision: string; description: string;
  nominalDimensionsMm: { width: number; height: number; depth: number };
  dimensionsMm: { width: number; height: number; depth: number };
  footprintType: string; confidenceLevel: CadConfidenceLevel; confidenceRationale: string; validationStatus: CadModelValidation;
  license: string; sourceReference: string; sourceUrl: string; format: 'STEP' | 'GLB' | 'Procedural Parametric' | 'KiCad 3D';
  verificationDate: string; inferredDimensions: string[]; replacementInstructions: string; connectedNets: string[]; disclaimerNote?: string; pins: ComponentPinDefinition[];
}

const pin = (id: string, pinNumber: number, label: string, signalType: ComponentPinDefinition['signalType'], nominalVoltageV: number, description: string, relativeX = 0, relativeY = 0): ComponentPinDefinition => ({ id, pinNumber, label, signalType, nominalVoltageV, description, relativeX, relativeY });

const make = (data: Partial<CadComponentMetadata> & Pick<CadComponentMetadata, 'id' | 'designatorPrefix' | 'name' | 'partNumber' | 'dimensionsMm'>): CadComponentMetadata => ({
  manufacturer: 'A definir', revision: 'baseline 2026-09-28', description: data.name,
  nominalDimensionsMm: data.dimensionsMm, footprintType: 'PENDING_PHYSICAL_RELEASE', confidenceLevel: 'C',
  confidenceRationale: 'Referência de engenharia; confirmar a unidade física antes de liberar montagem ou fabricação.',
  validationStatus: 'documented_reference', license: 'manufacturer-reference', sourceReference: 'FuelGuard engineering catalog', sourceUrl: 'https://github.com/Gustavo-prog0612/fuelguard-virtual',
  format: 'Procedural Parametric', verificationDate: '2026-09-28', inferredDimensions: [], replacementInstructions: 'Medir a unidade comprada e atualizar o registro de evidência.', connectedNets: [], pins: [], ...data,
});

export const FUELGUARD_CAD_LIBRARY: Record<string, CadComponentMetadata> = {
  esp32_s3_devkit: make({
    id: 'esp32_s3_devkit', designatorPrefix: 'U1', name: 'ESP32-S3-DevKitC-1-N8R8 v1.1', manufacturer: 'Espressif Systems', partNumber: 'ESP32-S3-DevKitC-1-N8R8',
    dimensionsMm: { width: 25.5, height: 68, depth: 12 }, nominalDimensionsMm: { width: 25.5, height: 68, depth: 12.8 }, footprintType: '2x22 headers 2.54 mm / span 22.86 mm', confidenceLevel: 'B', validationStatus: 'documented_reference', license: 'FuelGuard reconstruction from manufacturer reference; source redistribution terms apply', sourceReference: 'Espressif official DevKitC-1 v1.1 guide, DXF and PCB drawing', sourceUrl: 'https://docs.espressif.com/projects/esp-dev-kits/en/latest/esp32s3/esp32-s3-devkitc-1/user_guide_v1.1.html', format: 'GLB', inferredDimensions: ['Header height, connector body and component placement reconstructed from official references; validate against received unit'], connectedNets: ['+5V_VBUS', '+3.3V', 'GND', 'LEVEL_UART_RX', 'LEVEL_MODE_PROCESSED', 'BUZZER_CTRL', 'LID_INTERLOCK', 'SPI_CS', 'SPI_MOSI', 'SPI_SCK', 'SPI_MISO'], pins: [
      pin('3v3', 1, '3V3', 'power', 3.3, 'Saída regulada 3,3 V', -11.43, 30.48), pin('5v', 2, '5V (USB)', 'power', 5, 'VBUS da alimentação Micro-USB', -11.43, 27.94), pin('gnd', 3, 'GND', 'ground', 0, 'Terra comum', -11.43, 25.4), pin('gpio4', 4, 'IO4 (LED)', 'digital_out', 3.3, 'LED via R3 220 Ω', -11.43, 22.86), pin('gpio14', 14, 'IO14 (BUZZER)', 'digital_out', 3.3, 'Buzzer ativo', -11.43, 20.32), pin('gpio16', 16, 'IO16 (UART1_RX)', 'digital_in', 3.3, 'TX do SEN0311', -11.43, 17.78), pin('gpio7', 7, 'IO7 (LID)', 'digital_in', 3.3, 'MC-38', 11.43, 30.48), pin('gpio10', 10, 'IO10 (CS)', 'digital_out', 3.3, 'PN532 SS', 11.43, 22.86), pin('gpio11', 11, 'IO11 (MOSI)', 'spi_data', 3.3, 'PN532 MOSI', 11.43, 20.32), pin('gpio12', 12, 'IO12 (SCK)', 'spi_clock', 3.3, 'PN532 SCK', 11.43, 17.78), pin('gpio13', 13, 'IO13 (MISO)', 'spi_data', 3.3, 'PN532 MISO', 11.43, 15.24),
    ], replacementInstructions: 'Usar o esquemático, PCB e DXF oficiais da revisão v1.1; confirmar headers na unidade.',
  }),
  a02yyuw_sen0311: make({
    id: 'a02yyuw_sen0311', designatorPrefix: 'SEN1', name: 'DFRobot A02YYUW / SEN0311', manufacturer: 'DFRobot', partNumber: 'SEN0311', dimensionsMm: { width: 84.6, height: 29.6, depth: 12.5 }, footprintType: 'GLB de referência; suporte centralizado na tampa', confidenceLevel: 'B', validationStatus: 'documented_reference', license: 'FuelGuard reconstruction from DFRobot/Mouser mechanical reference', sourceReference: 'DFRobot SEN0311 wiki + A02YYUW mechanical drawing', sourceUrl: 'https://wiki.dfrobot.com/sen0311/', connectedNets: ['+3.3V', 'GND', 'LEVEL_UART_RX', 'LEVEL_MODE_PROCESSED'], inferredDimensions: ['Cabo 300 ± 10 mm; terminal PH2.0-4P; confirmar lote'], disclaimerNote: 'GLB reconstruído a partir do desenho mecânico; medir a unidade recebida antes de fabricar.', format: 'GLB', pins: [pin('vcc', 1, 'VCC (3V3)', 'power', 3.3, 'Alimentação em 3,3 V', 0, 3.81), pin('gnd', 2, 'GND', 'ground', 0, 'Retorno comum', 0, 1.27), pin('rx_mode', 3, 'RX (MODE)', 'digital_in', 3.3, 'HIGH seleciona saída processada', 0, -1.27), pin('tx', 4, 'TX (UART)', 'digital_out', 3.3, '9600 8N1 para GPIO16', 0, -3.81)],
  }),
  pn532_breakout: make({
    id: 'pn532_breakout', designatorPrefix: 'RFID1', name: 'ELECHOUSE PN532 NFC/RFID V4', manufacturer: 'ELECHOUSE', partNumber: 'NFC-PN532_V4', dimensionsMm: { width: 42.7, height: 40.4, depth: 4 }, nominalDimensionsMm: { width: 42.7, height: 40.4, depth: 4 }, footprintType: 'Header 1x8 2.54 mm; mating connector pending', confidenceLevel: 'C', validationStatus: 'documented_reference', sourceReference: 'ELECHOUSE V4; envelope nominal por referência V3', sourceUrl: 'https://www.elechouse.com/product/pn532-nfc-rfid-module-v4/', connectedNets: ['+3.3V', 'GND', 'SPI_CS', 'SPI_MOSI', 'SPI_SCK', 'SPI_MISO'], inferredDimensions: ['Header, furos, altura máxima e keepout da antena'], disclaimerNote: 'Confirmar revisão física, header, furos e antena antes do suporte.', pins: [pin('sck', 1, 'SCK', 'spi_clock', 3.3, 'SPI clock'), pin('miso', 2, 'MISO', 'spi_data', 3.3, 'PN532 para ESP32'), pin('mosi', 3, 'MOSI', 'spi_data', 3.3, 'ESP32 para PN532'), pin('ss', 4, 'SS/CS', 'digital_in', 3.3, 'Chip select'), pin('vcc', 5, 'VCC', 'power', 3.3, 'Alimentação'), pin('gnd', 6, 'GND', 'ground', 0, 'Terra'), pin('irq', 7, 'IRQ', 'digital_out', 3.3, 'Auxiliar não usado'), pin('rsto', 8, 'RSTO', 'digital_out', 3.3, 'Auxiliar não usado')],
  }),
  reed_switch: make({
    id: 'reed_switch', designatorPrefix: 'SW1', name: 'MC-38 Reed Switch + ímã', manufacturer: 'MC-38 family / TinyTronics reference', partNumber: 'MC-38-VENDOR-LOT-REFERENCE', dimensionsMm: { width: 27, height: 10, depth: 36 }, footprintType: 'GLB de referência; suporte externo vendor-lot-specific', confidenceLevel: 'C', validationStatus: 'documented_reference', sourceReference: 'MC-38 vendor reference dimensions', sourceUrl: 'https://www.tinytronics.nl/en/switches/magnetic-switches/door-switch-reed-relay-with-magnet', license: 'FuelGuard reconstruction from vendor reference dimensions', format: 'GLB', inferredDimensions: ['Família sem MPN único; cabo, gap e NO/NC dependem do lote'], disclaimerNote: 'Confirmar unidade comprada antes de fabricar.', connectedNets: ['LID_INTERLOCK', 'GND'], pins: [pin('pin1', 1, 'Sinal (IO7)', 'passive', 3.3, 'GPIO7 com pull-up interno', 0, 2.54), pin('pin2', 2, 'GND', 'ground', 0, 'Retorno comum', 0, -2.54)],
  }),
  breadboard_830: make({ id: 'breadboard_830', designatorPrefix: 'BB1', name: 'Protoboard MB-102 830 pontos', manufacturer: 'Vendor-lot-specific', partNumber: 'MB-102-830', dimensionsMm: { width: 165, height: 8.5, depth: 55 }, nominalDimensionsMm: { width: 165, height: 8.5, depth: 55 }, confidenceLevel: 'C', validationStatus: 'vendor_lot_specific', sourceReference: 'MB-102 reference datasheets', sourceUrl: 'https://handsontec.com/dataspecs/m102-830-bread-board.pdf', connectedNets: ['+5V_VBUS', '+3.3V', 'GND'], disclaimerNote: 'Medir o exemplar antes de congelar a bancada.' }),
  tank_cylinder: make({ id: 'tank_cylinder', designatorPrefix: 'TK1', name: 'Tanque cilíndrico acrílico FG-TANK-5L-CYL-R1', manufacturer: 'FuelGuard bench design', partNumber: 'FG-TANK-5L-CYL-R1', dimensionsMm: { width: 206, height: 168, depth: 206 }, footprintType: 'Cilindro acrílico paramétrico Ø206; tampa circular 4x M3', confidenceLevel: 'C', validationStatus: 'site_specific', sourceReference: 'Baseline paramétrica aprovada pelo projeto', sourceUrl: 'https://cadquery.github.io/', connectedNets: ['LID_INTERLOCK'], disclaimerNote: 'Baseline paramétrica: interno Ø200×160 mm; capacidade geométrica 5,0265 L; operação recomendada até aproximadamente 4,084 L; fabricar, medir e calibrar.' }),
  usb_cable_assembly: make({ id: 'usb_cable_assembly', designatorPrefix: 'PS1', name: 'Fonte/cabo USB-C 5 V / 3 A', manufacturer: 'A selecionar', partNumber: 'USB-C-5V-3A-CERTIFIED-PENDING', dimensionsMm: { width: 0, height: 0, depth: 0 }, confidenceLevel: 'D', validationStatus: 'vendor_lot_specific', sourceReference: 'Fonte externa da bancada', sourceUrl: 'https://www.usb.org/', connectedNets: ['+5V_VBUS', 'GND'], disclaimerNote: 'Fonte certificada e cabo ainda precisam ser selecionados.' }),
  led_indicator: make({ id: 'led_indicator', designatorPrefix: 'D1', name: 'LED verde Ø5 mm + resistor R3 220 Ω', manufacturer: 'Kingbright / equivalente', partNumber: 'WP7113GD + 220R', dimensionsMm: { width: 5, height: 8.6, depth: 5 }, nominalDimensionsMm: { width: 5, height: 8.6, depth: 5 }, footprintType: 'LED_THT:LED_D5.0mm + resistor a selecionar', confidenceLevel: 'B', validationStatus: 'documented_reference', license: 'FuelGuard reconstruction from manufacturer reference', sourceReference: 'Kingbright WP7113GD datasheet', sourceUrl: 'https://www.kingbrightusa.com/images/catalog/SPEC/WP7113GD.pdf', connectedNets: ['STATUS_LED_CTRL', 'GND'], pins: [pin('anode', 1, 'Anodo (via 220R)', 'passive', 3.3, 'GPIO4 através de R3'), pin('cathode', 2, 'Catodo', 'ground', 0, 'GND')] }),
  buzzer_active: make({ id: 'buzzer_active', designatorPrefix: 'BZ1', name: 'Buzzer ativo Same Sky CMI-1295IC-0385T', manufacturer: 'Same Sky', partNumber: 'CMI-1295IC-0385T', dimensionsMm: { width: 12, height: 9.5, depth: 12 }, nominalDimensionsMm: { width: 12, height: 9.5, depth: 12 }, footprintType: 'THT 2-pin; passo/polaridade pending', confidenceLevel: 'B', validationStatus: 'documented_reference', sourceReference: 'Same Sky official datasheet', sourceUrl: 'https://jp.sameskydevices.com/product/resource/cmi-1295ic-0385t.pdf', connectedNets: ['BUZZER_CTRL', 'GND'], inferredDimensions: ['Passo e polaridade dos terminais'], pins: [pin('ctrl', 1, 'CTRL / +', 'digital_in', 3.3, 'Comando GPIO14'), pin('gnd', 2, 'GND / -', 'ground', 0, 'Retorno comum')] }),
};
