/**
 * FuelGuard Virtual Test Bench — Cadastro Físico de Fiação e Chicotes (Wiring Registry)
 * Define todas as conexões físicas 3D entre componentes reais da bancada com rotas tubulares,
 * coordenadas espaciais nominais, bitolas AWG, grupos de redes e rastreabilidade com o esquemático.
 */

export type CableSignalGroup = 'power' | 'spi' | 'sensors' | 'usb';

export type CableSignalType =
  | 'power_5v'
  | 'power_3v3'
  | 'ground'
  | 'ultrasonic_trig'
  | 'ultrasonic_echo_5v'
  | 'ultrasonic_echo_safe'
  | 'spi_mosi'
  | 'spi_miso'
  | 'spi_sck'
  | 'spi_cs'
  | 'reed_interlock'
  | 'usb_data'
  | 'coaxial_rf'
  | 'led_status'
  | 'buzzer_signal';

export interface PhysicalCable {
  id: string;
  netName: string;
  label: string;
  group: CableSignalGroup;
  signalType: CableSignalType;
  colorHex: string;
  awgGauge: string;
  diameterMm: number;
  fromComponent: string;
  fromPin: string;
  toComponent: string;
  toPin: string;
  fromCoord: [number, number, number];
  toCoord: [number, number, number];
  waypoints: [number, number, number][];
  estimatedLengthMm: number;
  nominalVoltageV: number;
  description: string;
}

/**
 * Cadastro Canônico da Fiação Física da Bancada Didática FuelGuard
 * Coordenadas espaciais em milímetros no sistema de referência da bancada:
 * - Origem (0, 0, 0) no centro do tapete ESD
 * - Protoboard 830: Centro (-80, 7.5, 20)
 * - ESP32-S3: Centro (-110, 14, 20)
 * - Buffer SN74AHCT125N: Centro (-55, 14, 20)
 * - Divisor Resistivo: Centro (-35, 12, 20)
 * - Módulo JSN-SR04T: Centro (-75, 5, -50)
 * - Galão Didático 5L: Centro (85, 3.5, -10), Altura 150mm
 * - Tampa e PN532: Centro (85, 150..164, -10)
 */
export const PHYSICAL_WIRING_REGISTRY: PhysicalCable[] = [
  // =========================================================================
  // 1. ALIMENTAÇÃO & DISTRIBUIÇÃO DE TERRA (POWER & GND)
  // =========================================================================
  {
    id: 'W_5V_ESP_TO_RAIL',
    netName: '+5V_VBUS',
    label: '+5V VBUS (ESP32 Pin 2 -> Barramento Vermelho)',
    group: 'power',
    signalType: 'power_5v',
    colorHex: '#ef4444',
    awgGauge: 'AWG24',
    diameterMm: 1.1,
    fromComponent: 'esp32_s3_devkit',
    fromPin: 'Pin 2 (5V/VBUS)',
    toComponent: 'breadboard_830',
    toPin: 'Trilho +Superior (Pos 12)',
    fromCoord: [-110, 15, 9.5],
    toCoord: [-110, 12, -2.5],
    waypoints: [
      [-110, 15, 9.5],
      [-110, 24, 7],
      [-110, 23, 0],
      [-110, 12, -2.5],
    ],
    estimatedLengthMm: 35,
    nominalVoltageV: 5.0,
    description: 'Distribuição da tensão de 5V provida pelo conector USB para o trilho principal de alimentação.',
  },
  {
    id: 'W_GND_ESP_TO_RAIL',
    netName: 'GND',
    label: 'GND Comum (ESP32 Pin 3 -> Barramento Azul)',
    group: 'power',
    signalType: 'ground',
    colorHex: '#0f172a',
    awgGauge: 'AWG24',
    diameterMm: 1.1,
    fromComponent: 'esp32_s3_devkit',
    fromPin: 'Pin 3 (GND)',
    toComponent: 'breadboard_830',
    toPin: 'Trilho -Superior (Pos 14)',
    fromCoord: [-107.5, 15, 9.5],
    toCoord: [-107.5, 12, -5.5],
    waypoints: [
      [-107.5, 15, 9.5],
      [-107.5, 23, 6],
      [-107.5, 22, -1],
      [-107.5, 12, -5.5],
    ],
    estimatedLengthMm: 32,
    nominalVoltageV: 0.0,
    description: 'Referência equipotencial de terra entre microcontrolador e barramentos da protoboard.',
  },
  {
    id: 'W_5V_RAIL_TO_BUFFER',
    netName: '+5V_VCC',
    label: '+5V VCC (Barramento -> Buffer Pin 14)',
    group: 'power',
    signalType: 'power_5v',
    colorHex: '#ef4444',
    awgGauge: 'AWG24',
    diameterMm: 1.1,
    fromComponent: 'breadboard_830',
    fromPin: 'Trilho +Superior',
    toComponent: 'sn74ahct125n',
    toPin: 'Pin 14 (VCC 5V)',
    fromCoord: [-62.5, 12, -2.5],
    toCoord: [-62.5, 15, 16.2],
    waypoints: [
      [-62.5, 12, -2.5],
      [-62.5, 22, 2],
      [-62.5, 23, 12],
      [-62.5, 15, 16.2],
    ],
    estimatedLengthMm: 38,
    nominalVoltageV: 5.0,
    description: 'Alimentação de 5.0V para operação do buffer TTL SN74AHCT125N.',
  },
  {
    id: 'W_GND_RAIL_TO_BUFFER',
    netName: 'GND',
    label: 'GND Buffer (Barramento -> Buffer Pin 7)',
    group: 'power',
    signalType: 'ground',
    colorHex: '#0f172a',
    awgGauge: 'AWG24',
    diameterMm: 1.1,
    fromComponent: 'breadboard_830',
    fromPin: 'Trilho -Superior',
    toComponent: 'sn74ahct125n',
    toPin: 'Pin 7 (GND)',
    fromCoord: [-47.5, 12, -5.5],
    toCoord: [-47.5, 15, 23.8],
    waypoints: [
      [-47.5, 12, -5.5],
      [-47.5, 21, 2],
      [-47.5, 22, 18],
      [-47.5, 15, 23.8],
    ],
    estimatedLengthMm: 45,
    nominalVoltageV: 0.0,
    description: 'Terra de polarização do CI buffer e pino /1OE de habilitação amarrado ao GND.',
  },
  {
    id: 'W_3V3_ESP_TO_PN532',
    netName: '+3.3V',
    label: '+3.3V Lógica (ESP32 Pin 1 -> PN532 VCC)',
    group: 'power',
    signalType: 'power_3v3',
    colorHex: '#f97316',
    awgGauge: 'AWG24',
    diameterMm: 1.1,
    fromComponent: 'esp32_s3_devkit',
    fromPin: 'Pin 1 (3V3)',
    toComponent: 'pn532_breakout',
    toPin: 'Header Pin 1 (VCC 3V3)',
    fromCoord: [-112.5, 15, 9.5],
    toCoord: [66, 164, -16],
    waypoints: [
      [-112.5, 15, 9.5],
      [-100, 36, 12],
      [-20, 65, 5],
      [40, 120, -5],
      [66, 164, -16],
    ],
    estimatedLengthMm: 260,
    nominalVoltageV: 3.3,
    description: 'Alimentação regulada de 3.3V para o circuito de controle NFC PN532 na tampa.',
  },
  {
    id: 'W_GND_ESP_TO_PN532',
    netName: 'GND',
    label: 'GND NFC (Barramento Protoboard -> PN532 GND)',
    group: 'power',
    signalType: 'ground',
    colorHex: '#0f172a',
    awgGauge: 'AWG24',
    diameterMm: 1.1,
    fromComponent: 'breadboard_830',
    fromPin: 'Trilho -Superior',
    toComponent: 'pn532_breakout',
    toPin: 'Header Pin 2 (GND)',
    fromCoord: [-95, 12, -5.5],
    toCoord: [66, 164, -13.5],
    waypoints: [
      [-95, 12, -5.5],
      [-80, 38, -2],
      [0, 68, -8],
      [45, 122, -10],
      [66, 164, -13.5],
    ],
    estimatedLengthMm: 245,
    nominalVoltageV: 0.0,
    description: 'Retorno de terra de alta imunidade a ruídos para o leitor NFC.',
  },

  // =========================================================================
  // 2. TRANSDUTOR & SENSOR ULTRASSÔNICO (JSN-SR04T)
  // =========================================================================
  {
    id: 'W_5V_RAIL_TO_JSN',
    netName: '+5V_JSN',
    label: '+5V Ultrassônico (Trilho Protoboard -> JSN VCC)',
    group: 'sensors',
    signalType: 'power_5v',
    colorHex: '#ef4444',
    awgGauge: 'AWG24',
    diameterMm: 1.1,
    fromComponent: 'breadboard_830',
    fromPin: 'Trilho +Superior (Pos 40)',
    toComponent: 'jsn_sr04t',
    toPin: 'Header Pin 1 (5V)',
    fromCoord: [-75, 12, -2.5],
    toCoord: [-78.8, 6.5, -35.5],
    waypoints: [
      [-75, 12, -2.5],
      [-76, 22, -12],
      [-78, 16, -26],
      [-78.8, 6.5, -35.5],
    ],
    estimatedLengthMm: 52,
    nominalVoltageV: 5.0,
    description: 'Alimentação dedicada para excitação piezoelétrica de 40 kHz.',
  },
  {
    id: 'W_GND_RAIL_TO_JSN',
    netName: 'GND',
    label: 'GND Ultrassônico (Trilho Protoboard -> JSN GND)',
    group: 'sensors',
    signalType: 'ground',
    colorHex: '#0f172a',
    awgGauge: 'AWG24',
    diameterMm: 1.1,
    fromComponent: 'breadboard_830',
    fromPin: 'Trilho -Superior (Pos 42)',
    toComponent: 'jsn_sr04t',
    toPin: 'Header Pin 4 (GND)',
    fromCoord: [-71, 12, -5.5],
    toCoord: [-71.2, 6.5, -35.5],
    waypoints: [
      [-71, 12, -5.5],
      [-71, 20, -14],
      [-71, 15, -27],
      [-71.2, 6.5, -35.5],
    ],
    estimatedLengthMm: 48,
    nominalVoltageV: 0.0,
    description: 'Retorno de corrente de disparo e terra analógico do módulo.',
  },
  {
    id: 'W_TRIG_ESP_TO_BUFFER',
    netName: 'TRIG_3V3',
    label: 'Sinal TRIG 3V3 (ESP32 GPIO5 -> Buffer Pin 2)',
    group: 'sensors',
    signalType: 'ultrasonic_trig',
    colorHex: '#22c55e',
    awgGauge: 'AWG24',
    diameterMm: 1.1,
    fromComponent: 'esp32_s3_devkit',
    fromPin: 'Pin 5 (GPIO5)',
    toComponent: 'sn74ahct125n',
    toPin: 'Pin 2 (1A)',
    fromCoord: [-100, 15, 9.5],
    toCoord: [-60, 15, 23.8],
    waypoints: [
      [-100, 15, 9.5],
      [-90, 26, 16],
      [-75, 28, 20],
      [-60, 15, 23.8],
    ],
    estimatedLengthMm: 64,
    nominalVoltageV: 3.3,
    description: 'Pulso de comando de telemetria emitido pelo ESP32 (3.3V).',
  },
  {
    id: 'W_TRIG_BUFFER_TO_JSN',
    netName: 'TRIG_5V',
    label: 'Disparo TRIG 5V TTL (Buffer Pin 3 -> JSN TRIG)',
    group: 'sensors',
    signalType: 'ultrasonic_trig',
    colorHex: '#16a34a',
    awgGauge: 'AWG24',
    diameterMm: 1.1,
    fromComponent: 'sn74ahct125n',
    toComponent: 'jsn_sr04t',
    fromPin: 'Pin 3 (1Y)',
    toPin: 'Header Pin 2 (TRIG)',
    fromCoord: [-57.5, 15, 23.8],
    toCoord: [-76.3, 6.5, -35.5],
    waypoints: [
      [-57.5, 15, 23.8],
      [-62, 28, 8],
      [-72, 24, -18],
      [-76.3, 6.5, -35.5],
    ],
    estimatedLengthMm: 85,
    nominalVoltageV: 5.0,
    description: 'Pulso elevado para nível TTL 5.0V com alta imunidade a ruídos industriais.',
  },
  {
    id: 'W_ECHO_JSN_TO_DIVIDER',
    netName: 'ECHO_5V_RAW',
    label: 'Eco Bruto 5V (JSN ECHO -> Divisor R1 10k)',
    group: 'sensors',
    signalType: 'ultrasonic_echo_5v',
    colorHex: '#eab308',
    awgGauge: 'AWG24',
    diameterMm: 1.1,
    fromComponent: 'jsn_sr04t',
    toComponent: 'voltage_divider',
    fromPin: 'Header Pin 3 (ECHO)',
    toPin: 'Entrada Divisor (R1 Vin)',
    fromCoord: [-73.7, 6.5, -35.5],
    toCoord: [-39, 13, 20],
    waypoints: [
      [-73.7, 6.5, -35.5],
      [-65, 25, -15],
      [-48, 27, 8],
      [-39, 13, 20],
    ],
    estimatedLengthMm: 92,
    nominalVoltageV: 5.0,
    description: 'Sinal de eco de alta tensão (5.0V) emitido pelo transdutor.',
  },
  {
    id: 'W_ECHO_DIVIDER_TO_ESP',
    netName: 'ECHO_3V0_SAFE',
    label: 'Eco Atenuado 3.0V Seguro (Divisor Vout -> ESP32 GPIO6)',
    group: 'sensors',
    signalType: 'ultrasonic_echo_safe',
    colorHex: '#10b981',
    awgGauge: 'AWG24',
    diameterMm: 1.1,
    fromComponent: 'voltage_divider',
    toComponent: 'esp32_s3_devkit',
    fromPin: 'Saída Divisor (Vout)',
    toPin: 'Pin 6 (GPIO6)',
    fromCoord: [-35, 13, 20],
    toCoord: [-97.5, 15, 9.5],
    waypoints: [
      [-35, 13, 20],
      [-55, 27, 24],
      [-80, 26, 18],
      [-97.5, 15, 9.5],
    ],
    estimatedLengthMm: 88,
    nominalVoltageV: 3.0,
    description: 'Tensão atenuada para 3.00V, rigorosamente dentro do limite seguro do SoC ESP32 (Vmax 3.6V).',
  },
  {
    id: 'W_COAX_PROBE_CABLE',
    netName: 'ACOUSTIC_PIEZO_COAX',
    label: 'Cabo Coaxial Blindado RG-174 (Placa JSN -> Sonda na Tampa)',
    group: 'sensors',
    signalType: 'coaxial_rf',
    colorHex: '#18181b',
    awgGauge: 'Coaxial RG-174',
    diameterMm: 2.8,
    fromComponent: 'jsn_sr04t',
    toComponent: 'tank_cylinder',
    fromPin: 'Terminal Transdutor JSN',
    toPin: 'Sonda Ultrassônica Estanque M20',
    fromCoord: [-60, 6.5, -55],
    toCoord: [85, 155, -10],
    waypoints: [
      [-60, 6.5, -55],
      [-40, 32, -60],
      [15, 60, -50],
      [65, 110, -35],
      [85, 155, -10],
    ],
    estimatedLengthMm: 310,
    nominalVoltageV: 12.0,
    description: 'Chicote coaxial flexível de alta impedância com blindagem trançada contra interferências de RF.',
  },

  // =========================================================================
  // 3. BARRAMENTO SPI DO LEITOR NFC (PN532 NA TAMPA)
  // =========================================================================
  {
    id: 'W_SPI_CS',
    netName: 'SPI_CS',
    label: 'SPI Chip Select (ESP32 GPIO10 -> PN532 SS)',
    group: 'spi',
    signalType: 'spi_cs',
    colorHex: '#a855f7',
    awgGauge: 'AWG24',
    diameterMm: 1.1,
    fromComponent: 'esp32_s3_devkit',
    toComponent: 'pn532_breakout',
    fromPin: 'Pin 10 (GPIO10)',
    toPin: 'Header Pin 3 (SS)',
    fromCoord: [-87.5, 15, 30.5],
    toCoord: [66, 164, -11],
    waypoints: [
      [-87.5, 15, 30.5],
      [-70, 42, 28],
      [0, 80, 15],
      [50, 130, 2],
      [66, 164, -11],
    ],
    estimatedLengthMm: 255,
    nominalVoltageV: 3.3,
    description: 'Linha de habilitação de barramento SPI ativa em nível baixo.',
  },
  {
    id: 'W_SPI_MOSI',
    netName: 'SPI_MOSI',
    label: 'SPI Master Out (ESP32 GPIO11 -> PN532 MOSI)',
    group: 'spi',
    signalType: 'spi_mosi',
    colorHex: '#c084fc',
    awgGauge: 'AWG24',
    diameterMm: 1.1,
    fromComponent: 'esp32_s3_devkit',
    toComponent: 'pn532_breakout',
    fromPin: 'Pin 11 (GPIO11)',
    toPin: 'Header Pin 4 (MOSI)',
    fromCoord: [-85, 15, 30.5],
    toCoord: [66, 164, -8.5],
    waypoints: [
      [-85, 15, 30.5],
      [-68, 44, 27],
      [2, 82, 14],
      [52, 132, 1],
      [66, 164, -8.5],
    ],
    estimatedLengthMm: 250,
    nominalVoltageV: 3.3,
    description: 'Transmissão serial de comandos e autenticação para o transceptor NFC.',
  },
  {
    id: 'W_SPI_SCK',
    netName: 'SPI_SCK',
    label: 'SPI Clock (ESP32 GPIO12 -> PN532 SCK)',
    group: 'spi',
    signalType: 'spi_sck',
    colorHex: '#9333ea',
    awgGauge: 'AWG24',
    diameterMm: 1.1,
    fromComponent: 'esp32_s3_devkit',
    toComponent: 'pn532_breakout',
    fromPin: 'Pin 12 (GPIO12)',
    toPin: 'Header Pin 5 (SCK)',
    fromCoord: [-82.5, 15, 30.5],
    toCoord: [66, 164, -6],
    waypoints: [
      [-82.5, 15, 30.5],
      [-66, 46, 26],
      [4, 84, 13],
      [54, 134, 0],
      [66, 164, -6],
    ],
    estimatedLengthMm: 248,
    nominalVoltageV: 3.3,
    description: 'Sinal de sincronismo de relógio serial a 4.0 MHz.',
  },
  {
    id: 'W_SPI_MISO',
    netName: 'SPI_MISO',
    label: 'SPI Master In (PN532 MISO -> ESP32 GPIO13)',
    group: 'spi',
    signalType: 'spi_miso',
    colorHex: '#7e22ce',
    awgGauge: 'AWG24',
    diameterMm: 1.1,
    fromComponent: 'pn532_breakout',
    toComponent: 'esp32_s3_devkit',
    fromPin: 'Header Pin 6 (MISO)',
    toPin: 'Pin 13 (GPIO13)',
    fromCoord: [66, 164, -3.5],
    toCoord: [-80, 15, 30.5],
    waypoints: [
      [66, 164, -3.5],
      [56, 136, -1],
      [6, 86, 12],
      [-64, 48, 25],
      [-80, 15, 30.5],
    ],
    estimatedLengthMm: 246,
    nominalVoltageV: 3.3,
    description: 'Recepção de UID das tags ISO14443A lidas pela antena do galão.',
  },

  // =========================================================================
  // 4. INTERLOCK MAGNÉTICO DA TAMPA (REED SWITCH)
  // =========================================================================
  {
    id: 'W_REED_INTERLOCK',
    netName: 'LID_INTERLOCK',
    label: 'Interlock Magnético (Reed Switch -> ESP32 GPIO7)',
    group: 'sensors',
    signalType: 'reed_interlock',
    colorHex: '#0ea5e9',
    awgGauge: 'AWG24',
    diameterMm: 1.1,
    fromComponent: 'reed_switch',
    toComponent: 'esp32_s3_devkit',
    fromPin: 'Terminal N.A. (Tampa)',
    toPin: 'Pin 7 (GPIO7)',
    fromCoord: [135, 142, -10],
    toCoord: [-95, 15, 30.5],
    waypoints: [
      [135, 142, -10],
      [125, 95, 20],
      [60, 60, 40],
      [-30, 40, 38],
      [-95, 15, 30.5],
    ],
    estimatedLengthMm: 290,
    nominalVoltageV: 3.3,
    description: 'Circuito de segurança mecânica: detecta remoção da tampa do recipiente via ímã de neodímio.',
  },

  // =========================================================================
  // 5. CABO DE ALIMENTAÇÃO & SERIAL USB-C
  // =========================================================================
  {
    id: 'W_USBC_MAIN',
    netName: 'USB_5V_POWER_DATA',
    label: 'Cabo USB-C Macho Blindado (Host/PC -> ESP32-S3 DevKit)',
    group: 'usb',
    signalType: 'usb_data',
    colorHex: '#334155',
    awgGauge: 'AWG28/AWG24 Combo',
    diameterMm: 3.6,
    fromComponent: 'esp32_s3_devkit',
    toComponent: 'external_host',
    fromPin: 'Porta USB-UART Type-C',
    toPin: 'Host PC / Fonte Bancada',
    fromCoord: [-110, 16, 54],
    toCoord: [-160, 5, 160],
    waypoints: [
      [-110, 16, 54],
      [-115, 15, 75],
      [-130, 12, 110],
      [-160, 5, 160],
    ],
    estimatedLengthMm: 140,
    nominalVoltageV: 5.0,
    description: 'Cabo blindado trançado de alta velocidade para alimentação e console serial 115200 bps.',
  },

  // =========================================================================
  // 6. INDICADORES & ALARME DIDÁTICO (LED & BUZZER)
  // =========================================================================
  {
    id: 'W_LED_STATUS',
    netName: 'STATUS_LED_NET',
    label: 'Status LED Drive (ESP32 GPIO4 -> LED Verde D1)',
    group: 'sensors',
    signalType: 'led_status',
    colorHex: '#22c55e',
    awgGauge: 'AWG24',
    diameterMm: 1.1,
    fromComponent: 'esp32_s3_devkit',
    toComponent: 'led_indicator',
    fromPin: 'Pin 4 (IO4)',
    toPin: 'Anodo (D1 via 1k)',
    fromCoord: [-110, 15, 12],
    toCoord: [-20, 14, 22],
    waypoints: [
      [-110, 15, 12],
      [-90, 22, 16],
      [-50, 20, 20],
      [-20, 14, 22],
    ],
    estimatedLengthMm: 95,
    nominalVoltageV: 3.3,
    description: 'Acionamento do sinalizador luminoso verde para indicar estado do ciclo de medição e prontidão da bancada.',
  },
  {
    id: 'W_BUZZER_CTRL',
    netName: 'BUZZER_CTRL',
    label: 'Disparo Buzzer Alarme (ESP32 GPIO14 -> Buzzer + BZ1)',
    group: 'sensors',
    signalType: 'buzzer_signal',
    colorHex: '#f59e0b',
    awgGauge: 'AWG24',
    diameterMm: 1.1,
    fromComponent: 'esp32_s3_devkit',
    toComponent: 'buzzer_piezo',
    fromPin: 'Pin 14 (IO14)',
    toPin: 'Terminal + (Positivo)',
    fromCoord: [-95, 15, 15],
    toCoord: [-5, 15, 23.8],
    waypoints: [
      [-95, 15, 15],
      [-70, 24, 18],
      [-30, 22, 22],
      [-5, 15, 23.8],
    ],
    estimatedLengthMm: 100,
    nominalVoltageV: 3.3,
    description: 'Sinal de áudio para avisos sonoros de leitura NFC bem-sucedida e alerta de remoção indevida da tampa.',
  },
  {
    id: 'W_BUZZER_GND',
    netName: 'GND',
    label: 'Retorno GND Buzzer (Buzzer - BZ1 -> Barramento GND)',
    group: 'power',
    signalType: 'ground',
    colorHex: '#0f172a',
    awgGauge: 'AWG24',
    diameterMm: 1.1,
    fromComponent: 'buzzer_piezo',
    toComponent: 'breadboard_830',
    fromPin: 'Terminal - (Negativo)',
    toPin: 'Trilho -Inferior (Pos 50)',
    fromCoord: [-5, 15, 16.2],
    toCoord: [-5, 12, 32.5],
    waypoints: [
      [-5, 15, 16.2],
      [-5, 18, 24],
      [-5, 12, 32.5],
    ],
    estimatedLengthMm: 25,
    nominalVoltageV: 0.0,
    description: 'Retorno do transdutor piezoelétrico ao trilho de terra de baixa impedância.',
  },
];
